### ISSUE TITLE
支援 OpenCC ver.1.0.3

### ISSUE THREAD

**Issue by amowu** [amowu/alfred-chinese-converter#1]
新增的配置文件：
- `tw2sp.json` 繁體（臺灣正體標準）到簡體並轉換爲中國大陸常用詞彙
- `t2tw.json` 繁體（OpenCC 標準）到臺灣正體
- `t2hk.json` 繁體（OpenCC 標準）到香港繁體（香港小學學習字詞表標準）

**Comment by hanksudo** [comment]
alfred list 只能有九個, 全加會超過。

`tw2sp.json` 感覺比較實用
